##################
## Users editing their own data
#################

# Create a customer account after succesfully logging in.
mutation UpsertCustomer(
  $firstName: String!
  $lastName: String!
  $email: String!
  $phone: String!
  $acceptsMarketing: Boolean!
) @auth(level: USER) {
  customer_upsert(
    data: {
      id_expr: "auth.uid"
      firstName: $firstName
      lastName: $lastName
      email: $email
      phone: $phone
      acceptsMarketing: $acceptsMarketing
    }
  )
}

# Create a new review
mutation CreateProductReview(
  $productId: String!
  $rating: Int!
  $content: String!
) @auth(level: USER) {
  productReview_insert(
    data: {
      productId: $productId
      customerId_expr: "auth.uid"
      rating: $rating
      content: $content
      contentEmbedding_embed: { model: "text-embedding-005", text: $content }
    }
  )
}

###############
## Update customer data with an admin contextin Stripe webhooks
#############

mutation CreateOrder(
  $chargeId: String
  $customerId: String
  $shippingStreet1: String!
  $shippingStreet2: String
  $shippingCity: String!
  $shippingState: String!
  $shippingZip: String!
  $paymentIntentId: String
  $receiptUrl: String
  $subtotalPrice: Float!
  $totalTax: Float!
  $totalShippingPrice: Float!
  $totalPrice: Float!
  $financialStatus: String!
  $fulfillmentStatus: String!
) @auth(level: NO_ACCESS) {
  order_insert(
    data: {
      customerId: $customerId
      shippingStreet1: $shippingStreet1
      shippingStreet2: $shippingStreet2
      shippingCity: $shippingCity
      shippingState: $shippingState
      shippingZip: $shippingZip
      chargeId: $chargeId
      paymentIntentId: $paymentIntentId
      receiptUrl: $receiptUrl
      subtotalPrice: $subtotalPrice
      totalTax: $totalTax
      totalShippingPrice: $totalShippingPrice
      totalPrice: $totalPrice
      financialStatus: $financialStatus
      fulfillmentStatus: $fulfillmentStatus
    }
  )
}

mutation CreateOrderItem($orderId: UUID!, $productId: String!, $quantity: Int!, $price: Float!)
@auth(level: NO_ACCESS) {
  orderItem_insert(
    data: {
      order: { id: $orderId }
      product: { id: $productId }
      quantity: $quantity
      price: $price
    }
  )
}

mutation UpdateOrderByPaymentIntentId(
  $paymentIntentId: String!
  $financialStatus: String
  $fulfillmentStatus: String
  $receiptUrl: String
  $processedAt: Timestamp
  $chargeId: String
) @auth(level: NO_ACCESS) {
  order_update(
    first: { where: { paymentIntentId: { eq: $paymentIntentId } } }
    data: {
      financialStatus: $financialStatus
      fulfillmentStatus: $fulfillmentStatus
      receiptUrl: $receiptUrl
      processedAt: $processedAt
      chargeId: $chargeId
    }
  )
}

mutation UpdateOrderByChargeId(
  $financialStatus: String
  $fulfillmentStatus: String
  $receiptUrl: String
  $processedAt: Timestamp
  $chargeId: String
) @auth(level: NO_ACCESS) {
  order_update(
    first: { where: { chargeId: { eq: $chargeId } } }
    data: {
      financialStatus: $financialStatus
      fulfillmentStatus: $fulfillmentStatus
      receiptUrl: $receiptUrl
      processedAt: $processedAt
    }
  )
}
